### A simple get request to the test endpoint. No need for login
GET http://localhost:7070/api/auth/test/

### Create a new user - this one will only get a USER role by default
POST http://localhost:7070/api/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST http://localhost:7070/api/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    //console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET http://localhost:7070/api/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET http://localhost:7070/api/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST http://localhost:7070/api/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon
Authorization: Bearer {{jwt_token}}
###

GET http://localhost:7070/api/pokemon/1
Authorization: Bearer {{jwt_token}}
###

POST http://localhost:7070/api/pokemon
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 1,
  "name": "bulbasaur2",
  "height": 7.0,
  "weight": 69.0,
  "types": [
    "grass",
    "poison"
  ],
  "spriteDefault": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/1.png",
  "spriteShiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/shiny/1.png",
  "officialArtDefault": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
  "officialArtShiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/1.png",
  "color": "green",
  "eggGroups": [
    "monster",
    "plant"
  ],
  "evolutionChain": 1,
  "flavorTextEntries": "BULBASAUR can be seen napping in bright\nsunlight. There is a seed on its back.\nBy soaking up the sun’s rays, the seed\ngrows progressively larger.",
  "habitat": "grassland",
  "mythical": false,
  "legendary": false
}


###

PUT http://localhost:7070/api/pokemon/6
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "id": 6,
  "name": "Green guy",
  "height": 7.0,
  "weight": 69.0,
  "types": [
    "grass",
    "poison"
  ],
  "spriteDefault": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/1.png",
  "spriteShiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/shiny/1.png",
  "officialArtDefault": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
  "officialArtShiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/1.png",
  "color": "green",
  "eggGroups": [
    "monster",
    "plant"
  ],
  "evolutionChain": 1,
  "flavorTextEntries": "BULBASAUR can be seen napping in bright\nsunlight. There is a seed on its back.\nBy soaking up the sun’s rays, the seed\ngrows progressively larger.",
  "habitat": "grassland",
  "mythical": false,
  "legendary": false
}

###

DELETE http://localhost:7070/api/pokemon/1
Authorization: Bearer {{jwt_token}}
###

GET http://localhost:7070/api/pokemon/evolution_chain/1
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/rarity/legendary
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/rarity/mythical
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/rarity/common
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/habitat/grassland
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/type/fire
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/egg_group/monster
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/color/green
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokedex
Authorization: Bearer {{jwt_token}}
###

GET http://localhost:7070/api/pokedex/1
Authorization: Bearer {{jwt_token}}
###

GET http://localhost:7070/api/pokedex/evolution_chain/1
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokedex/rarity/legendary
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokedex/rarity/mythical
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokedex/rarity/common
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokedex/habitat/grassland
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/type/fire
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/egg_group/monster
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/pokemon/color/green
Authorization: Bearer {{jwt_token}}

###

GET http://localhost:7070/api/user/user/favorites
Authorization: Bearer {{jwt_token}}

###

PUT http://localhost:7070/api/user/user/favorites/add/1
Authorization: Bearer {{jwt_token}}

###

PUT http://localhost:7070/api/user/user/favorites/remove/1
Authorization: Bearer {{jwt_token}}

###